export const admin = {
  title: "Privacy Sprint · Admin",
  listTitle: "Submissões",
  detailTitle: "Submissão",
  intro: "Revisão, julgamento e acompanhamento dos pagamentos do Privacy Sprint.",
  noindex: "Área restrita. O conteúdo desta página não deve aparecer em buscadores.",
  columns: {
    number: "Nº",
    project: "Projeto",
    team: "Time",
    category: "Categoria",
    tech: "Tech",
    created: "Enviado em",
    updated: "Atualizado em",
    status: "Status",
    score: "Nota",
    judges: "Juízes",
    winner: "Vencedor",
    pool: "Pool",
    payout: "Pagamento",
  },
  filters: {
    all: "Todos",
    category: "Categoria",
    tech: "Tech",
    status: "Status",
    apply: "Filtrar",
    clear: "Limpar",
  },
  actions: {
    hide: "Ocultar",
    unhide: "Reexibir",
    disqualify: "Desclassificar",
    reinstate: "Reintegrar",
    markWinner: "Marcar como vencedor",
    unmarkWinner: "Remover vencedor",
    save: "Salvar",
    saveScore: "Salvar nota",
    export: "Exportar CSV",
    back: "Voltar para a lista",
    applyFilters: "Aplicar filtros",
    saveModeration: "Salvar moderação",
    savePayout: "Salvar pagamento",
  },
  fields: {
    adminNotes: "Notas internas",
    disqualifyReason: "Motivo (fica nas notas internas)",
    prizePool: "Pool de prêmio",
    payoutStatus: "Status do pagamento",
    payoutWarning:
      "Não cole o link de pagamento aqui. Links são ao portador: quem tiver, resgata. O banco registra só o status.",
    judgeNotes: "Observações do juiz",
    contactName: "Nome de contato",
    contactEmail: "E-mail de contato",
    contactTelegram: "Telegram",
    contactWhatsApp: "WhatsApp",
    acceptedRules: "Regras aceitas",
    repository: "Repositório",
    changes: "Mudanças do sprint",
    proof: "Prova",
    demo: "Vídeo de demo",
    writeup: "Texto de privacidade",
    colosseum: "Página no Colosseum",
    website: "Site do projeto",
    members: "Integrantes",
    created: "Criado em (BRT)",
    updated: "Atualizado em (BRT)",
    status: "Status",
    winner: "Vencedor",
    payout: "Pagamento",
    category: "Categoria",
    tech: "Construído com",
    project: "Projeto",
    team: "Time",
    xAccount: "Conta do X conectada",
    number: "Número",
    disqualifiedStatus: "Desclassificado",
    submittedStatus: "Enviado",
    hiddenStatus: "Oculto",
    winnerYes: "Sim",
    winnerNo: "Não",
    selectPool: "Selecione o pool",
    selectStatus: "Selecione o status",
    dashboard: "Administração",
    detail: "Detalhes da submissão",
    slug: "Identificador",
    scores: "Notas dos jurados",
    scoreOutOfTen: "/ 10",
    none: "—",
  },
  winners: {
    title: "Vencedores",
    counter: (cloak: number, zcash: number) => `Cloak ${cloak}/5 · Zcash ${zcash}/5`,
    over: (pool: string) => `Atenção: o pool ${pool} passou de 5 vencedores.`,
  },
  judging: {
    title: "Julgamento",
    criteria: "Critério",
    weight: "Peso",
    guidance: "O que a gente procura",
    scoreLabel: "Nota (0 a 10)",
    weighted: "Nota ponderada",
    judges: "juízes",
    noScores: "Sem notas ainda",
    scoreCriteria: [
      {
        key: "privacy_impact",
        label: "Impacto de privacidade",
        weight: "30%",
        guidance: "Protege algo real; o texto deixa claro o que fica escondido, de quem, e o que se ganha.",
      },
      {
        key: "execution",
        label: "Produto funcionando e execução",
        weight: "30%",
        guidance: "Roda; as transações ou o app provam isso.",
      },
      {
        key: "project_fit",
        label: "Encaixe com o projeto do Hackathon",
        weight: "20%",
        guidance: "Deixa a submissão principal mais forte; o negócio é claro.",
      },
      {
        key: "ux_presentation",
        label: "UX e apresentação",
        weight: "20%",
        guidance: "Alguém de fora de cripto entenderia e usaria; o vídeo é claro.",
      },
    ],
  },
  empty: "Nenhuma submissão encontrada.",
  errors: {
    invalid: "Dados inválidos. Confira os campos e tente novamente.",
    save: "Não foi possível salvar agora. Tente novamente.",
    unauthorized: "Acesso não autorizado.",
  },
} as const;
