export const admin = {
  title: "Privacy Sprint · Admin",
  listTitle: "Submissões",
  detailTitle: "Submissão",
  columns: {
    number: "Nº",
    project: "Projeto",
    team: "Time",
    category: "Categoria",
    tech: "Tech",
    created: "Enviado em",
    updated: "Atualizado em",
    status: "Status",
    score: "Nota",
    judges: "Juízes",
    winner: "Vencedor",
    pool: "Pool",
    payout: "Pagamento",
  },
  filters: {
    all: "Todos",
    category: "Categoria",
    tech: "Tech",
    status: "Status",
    apply: "Filtrar",
    clear: "Limpar",
  },
  actions: {
    hide: "Ocultar",
    unhide: "Reexibir",
    disqualify: "Desclassificar",
    reinstate: "Reintegrar",
    markWinner: "Marcar como vencedor",
    unmarkWinner: "Remover vencedor",
    save: "Salvar",
    saveScore: "Salvar nota",
    export: "Exportar CSV",
    back: "Voltar para a lista",
  },
  fields: {
    adminNotes: "Notas internas",
    disqualifyReason: "Motivo (fica nas notas internas)",
    prizePool: "Pool de prêmio",
    payoutStatus: "Status do pagamento",
    payoutWarning:
      "Não cole o link de pagamento aqui. Links são ao portador: quem tiver, resgata. O banco registra só o status.",
    judgeNotes: "Observações do juiz",
  },
  winners: {
    title: "Vencedores",
    counter: (cloak: number, zcash: number) => `Cloak ${cloak}/5 · Zcash ${zcash}/5`,
    over: (pool: string) => `Atenção: o pool ${pool} passou de 5 vencedores.`,
  },
  judging: {
    title: "Julgamento",
    criteria: "Critério",
    weight: "Peso",
    guidance: "O que a gente procura",
    scoreLabel: "Nota (0 a 10)",
    weighted: "Nota ponderada",
    judges: "juízes",
    noScores: "Sem notas ainda",
  },
  empty: "Nenhuma submissão encontrada.",
} as const;
